export const apiConfig = {
  AUTH_ID: process.env.REACT_APP_AUTH_ID,
  NETWORK_KEY: process.env.REACT_APP_API_KEY_NETWORK,
  NETWORK_KEY_BOBUK: process.env.REACT_APP_API_KEY_NETWORK_BOBUK,
  EMAIL: process.env.REACT_APP_API_EMAIL,
  PASSWORD: process.env.REACT_APP_API_PASSWORD,
}
